# Generated by Django 5.2.1 on 2025-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alhana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
